### ISSUE TITLE
Submenu doesn't close when mouse leaves then enters parent

### ISSUE THREAD

**Issue by IanLunn** [joeldbirch/superfish#127]
When the cursor is moved out of a submenu then back into a parent link that doesn't have a submenu associated with it, the previous submenu stays open. The submenu correctly closes if the parent link has its own submenu, but not when it doesn't.

![screen shot 2014-10-21 at 14 50](https://cloud.githubusercontent.com/assets/694641/4719475/fbd653e4-5929-11e4-8671-f97894acac0f.png)

![screen shot 2014-10-21 at 14](https://cloud.githubusercontent.com/assets/694641/4719514/461c7e74-592a-11e4-946b-c51baf2cc281.png)

**Comment by joeldbirch** [comment]
I think I'd like to leave this as is for now because the behaviour helps navbar-style menus. They benefit from not instantly cancelling the submenu closing delay if the user's cursor happens across top level items that do not hold submenus.

However, you can get the behaviour you prefer by setting the `popUpSelector` option to `'*'` upon initialisation, instead of altering the Superfish code. Eg:

```JS
jQuery(document).ready(function(){
    jQuery('.sf-menu').superfish({
        /* other initialisation options here, then: */
        popUpSelector: '*'
    });
});
```
