### ISSUE TITLE
Dead code due to error in use of .data()

### ISSUE THREAD

**Issue by daviddeutsch** [joeldbirch/superfish#155]
Example:
```javascript
if ($this.data('sf-options')) {
	return false;
}
```
(in the `init` function)

jQuery `.data()` has a tricky behavior that not many people know about: [It uses camelcasing](http://stackoverflow.com/questions/7286607/jquery-camel-case-mapping-from-data-attribute-names-to-data-keys). So in the above code, you'd actually want to do
```javascript
$this.data('sfOptions')
```
to get consistent behavior.

However: It seems like the above code is actually an error, since it would exit the function that does all the initialization early. That "bug" just never occurred because of the wrong use of `.data()` 😉

I would recommend converting all calls to the correct casing to avoid weird behavior.

**Comment by joeldbirch** [comment]
Wow, okay, thanks! I'll take a look at this.

**Comment by joeldbirch** [comment]
I've had a look and it appears that the non-camel-cased version is still working in both versions of jQuery, although of course I agree that it should certainly be camel-cased. The following code returns true in Chrome's console: `if ($('.sf-menu').data('sf-options')) true;` and it successfully returns the options object.

I'm not sure the code is an error either, because its purpose is to intentionally exit the initialisation function if the menu is already initialised. Does this make sense, or am I missing something?

Anyway, thanks for the report. I'll definitely switch to camel-casing for data attributes from now on! It will be in the next release.

**Comment by daviddeutsch** [comment]
Thanks, @joeldbirch!

The issue with detecting `sfOptions` is that I had assumed that I can pass options into superfish via markup instead of having to initialize it. If that was supported, the code would be an issue.

Perhaps switch to a dedicated `sfInitialized` just to make it clear?
